/**
 * exportUtils.ts - HTML export utilities for reports
 */

import { SaveHTMLExport } from '../../wailsjs/go/main/App';

export interface ExportData {
    type: 'weekly' | 'monthly' | 'yearly';
    title: string;
    dateRange: string;
    data: any;
}

/**
 * Generate HTML for weekly report
 */
export function generateWeeklyHTML(data: {
    dateRange: string;
    dailyPercentages: number[];
    weeklyAverage: number;
}): string {
  const days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];

    const barsHTML = data.dailyPercentages.map((pct, i) => `
    <div class="bar-container">
      <div class="bar" style="height: ${pct}%;">
        <span class="bar-value">${Math.round(pct)}%</span>
      </div>
      <span class="bar-label">${days[i]}</span>
    </div>
  `).join('');

    return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Weekly Report - ${data.dateRange}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #f5f5f5; padding: 40px; }
    .report { background: white; border-radius: 16px; padding: 32px; max-width: 800px; margin: 0 auto; box-shadow: 0 4px 20px rgba(0,0,0,0.1); }
    .header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 32px; }
    .title { font-size: 24px; font-weight: 600; color: #1a1a1a; }
    .subtitle { font-size: 14px; color: #888; margin-top: 4px; }
    .average { text-align: right; }
    .average-value { font-size: 32px; font-weight: 700; color: #34C759; }
    .average-label { font-size: 12px; color: #888; text-transform: uppercase; }
    .chart { display: flex; justify-content: space-between; align-items: flex-end; height: 200px; padding: 20px 0; border-top: 1px solid #eee; }
    .bar-container { flex: 1; display: flex; flex-direction: column; align-items: center; height: 100%; }
    .bar { width: 40px; background: linear-gradient(180deg, #34C759 0%, #2FB350 100%); border-radius: 8px 8px 0 0; display: flex; align-items: flex-start; justify-content: center; min-height: 4px; }
    .bar-value { font-size: 11px; font-weight: 600; color: white; padding: 4px; }
    .bar-label { font-size: 12px; color: #666; margin-top: 8px; }
    .footer { margin-top: 24px; padding-top: 16px; border-top: 1px solid #eee; text-align: center; color: #888; font-size: 12px; }
  </style>
</head>
<body>
  <div class="report">
    <div class="header">
      <div>
        <h1 class="title">Weekly Progress</h1>
        <p class="subtitle">${data.dateRange}</p>
      </div>
      <div class="average">
        <div class="average-value">${Math.round(data.weeklyAverage)}%</div>
        <div class="average-label">Weekly Average</div>
      </div>
    </div>
    <div class="chart">
      ${barsHTML}
    </div>
    <div class="footer">
      Generated by PLAN • ${new Date().toLocaleDateString()}
    </div>
  </div>
</body>
</html>`;
}

/**
 * Generate HTML for monthly report
 */
export function generateMonthlyHTML(data: {
    monthName: string;
    year: number;
    weeklyAverages: number[];
    trendDirection: string;
}): string {
    const monthlyAvg = data.weeklyAverages.length > 0
        ? Math.round(data.weeklyAverages.reduce((a, b) => a + b, 0) / data.weeklyAverages.length)
        : 0;

    const weeksHTML = data.weeklyAverages.map((avg, i) => `
    <div class="week-block" style="background: rgba(52, 199, 89, ${avg > 0 ? 0.3 + (avg / 100) * 0.7 : 0.1});">
      <span class="week-label">Week ${i + 1}</span>
      <span class="week-value">${Math.round(avg)}%</span>
    </div>
  `).join('');

    const trendArrow = data.trendDirection === 'up' ? '↗' : data.trendDirection === 'down' ? '↘' : '→';

    return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Monthly Report - ${data.monthName} ${data.year}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #f5f5f5; padding: 40px; }
    .report { background: white; border-radius: 16px; padding: 32px; max-width: 800px; margin: 0 auto; box-shadow: 0 4px 20px rgba(0,0,0,0.1); }
    .header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 32px; }
    .title { font-size: 24px; font-weight: 600; color: #1a1a1a; }
    .trend { display: flex; align-items: center; gap: 8px; color: #888; }
    .trend-arrow { font-size: 20px; }
    .weeks { display: flex; gap: 12px; justify-content: center; flex-wrap: wrap; margin-bottom: 32px; }
    .week-block { padding: 20px 24px; border-radius: 12px; text-align: center; min-width: 100px; }
    .week-label { display: block; font-size: 12px; color: #1a1a1a; opacity: 0.7; margin-bottom: 4px; }
    .week-value { font-size: 24px; font-weight: 700; color: #1a1a1a; }
    .summary { text-align: center; padding: 24px; background: #f5f5f5; border-radius: 12px; }
    .summary-value { font-size: 48px; font-weight: 700; color: #34C759; }
    .summary-label { font-size: 14px; color: #888; text-transform: uppercase; margin-top: 4px; }
    .footer { margin-top: 24px; padding-top: 16px; border-top: 1px solid #eee; text-align: center; color: #888; font-size: 12px; }
  </style>
</head>
<body>
  <div class="report">
    <div class="header">
      <h1 class="title">${data.monthName} ${data.year}</h1>
      <div class="trend">
        <span class="trend-arrow">${trendArrow}</span>
        <span>${data.trendDirection}</span>
      </div>
    </div>
    <div class="weeks">
      ${weeksHTML}
    </div>
    <div class="summary">
      <div class="summary-value">${monthlyAvg}%</div>
      <div class="summary-label">Monthly Average</div>
    </div>
    <div class="footer">
      Generated by PLAN • ${new Date().toLocaleDateString()}
    </div>
  </div>
</body>
</html>`;
}

/**
 * Generate HTML for yearly report
 */
export function generateYearlyHTML(data: {
    year: number;
    monthlyAverages: number[];
    mostConsistentMonth: number;
    yearTotal: number;
}): string {
    const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
    const fullMonths = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];

    const barsHTML = data.monthlyAverages.map((avg, i) => `
    <div class="month-container">
      <div class="month-bar" style="height: ${avg}%;">
        ${avg > 15 ? `<span class="month-value">${Math.round(avg)}%</span>` : ''}
      </div>
      <span class="month-label">${months[i]}</span>
      ${i === data.mostConsistentMonth && avg > 0 ? '<span class="consistent">★</span>' : ''}
    </div>
  `).join('');

    return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Yearly Report - ${data.year}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #f5f5f5; padding: 40px; }
    .report { background: white; border-radius: 16px; padding: 32px; max-width: 900px; margin: 0 auto; box-shadow: 0 4px 20px rgba(0,0,0,0.1); }
    .header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 32px; }
    .title { font-size: 28px; font-weight: 700; color: #1a1a1a; }
    .average { text-align: right; }
    .average-value { font-size: 36px; font-weight: 700; color: #34C759; }
    .average-label { font-size: 12px; color: #888; text-transform: uppercase; }
    .chart { display: flex; justify-content: space-between; align-items: flex-end; height: 250px; padding: 20px 0; border-top: 1px solid #eee; }
    .month-container { flex: 1; display: flex; flex-direction: column; align-items: center; height: 100%; position: relative; }
    .month-bar { width: 32px; background: linear-gradient(180deg, #34C759 0%, #2FB350 100%); border-radius: 6px 6px 0 0; display: flex; align-items: flex-start; justify-content: center; min-height: 4px; }
    .month-value { font-size: 10px; font-weight: 600; color: white; padding: 3px; }
    .month-label { font-size: 11px; color: #666; margin-top: 8px; }
    .consistent { position: absolute; bottom: -20px; color: #FFD700; font-size: 14px; }
    .insight { margin-top: 32px; padding: 20px; background: #f9f9f9; border-radius: 12px; text-align: center; }
    .insight p { color: #666; font-size: 14px; }
    .insight strong { color: #34C759; }
    .footer { margin-top: 24px; padding-top: 16px; border-top: 1px solid #eee; text-align: center; color: #888; font-size: 12px; }
  </style>
</head>
<body>
  <div class="report">
    <div class="header">
      <h1 class="title">${data.year} Overview</h1>
      <div class="average">
        <div class="average-value">${Math.round(data.yearTotal)}%</div>
        <div class="average-label">Yearly Average</div>
      </div>
    </div>
    <div class="chart">
      ${barsHTML}
    </div>
    ${data.monthlyAverages[data.mostConsistentMonth] > 0 ? `
    <div class="insight">
      <p><strong>${fullMonths[data.mostConsistentMonth]}</strong> was your most consistent month</p>
    </div>
    ` : ''}
    <div class="footer">
      Generated by PLAN • ${new Date().toLocaleDateString()}
    </div>
  </div>
</body>
</html>`;
}

/**
 * Export report to HTML file
 */
export async function exportToHTML(
    type: 'weekly' | 'monthly' | 'yearly',
    data: any
): Promise<string> {
    let html = '';
    let filename = '';
    const timestamp = new Date().toISOString().slice(0, 10);

    switch (type) {
        case 'weekly':
            html = generateWeeklyHTML(data);
            filename = `PLAN-Weekly-Report-${timestamp}.html`;
            break;
        case 'monthly':
            html = generateMonthlyHTML(data);
            filename = `PLAN-Monthly-Report-${data.monthName}-${data.year}.html`;
            break;
        case 'yearly':
            html = generateYearlyHTML(data);
            filename = `PLAN-Yearly-Report-${data.year}.html`;
            break;
    }

    const savedPath = await SaveHTMLExport(filename, html);
    return savedPath;
}
