// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTask(arg1:string,arg2:string,arg3:string):Promise<main.TaskTemplate>;

export function DeleteTask(arg1:string):Promise<void>;

export function GetExportPath():Promise<string>;

export function GetMonthlyReport(arg1:number,arg2:number):Promise<Record<string, any>>;

export function GetStreaks():Promise<Record<string, any>>;

export function GetTaskTemplates():Promise<Array<main.TaskTemplate>>;

export function GetTasksForDate(arg1:string):Promise<Array<main.TaskTemplate>>;

export function GetWeeklyReport(arg1:string):Promise<Record<string, any>>;

export function GetYearlyReport(arg1:number):Promise<Record<string, any>>;

export function IsWeekExported(arg1:string):Promise<boolean>;

export function LoadDay(arg1:string):Promise<Record<string, number>>;

export function LoadWeek(arg1:string):Promise<Record<string, Record<string, number>>>;

export function MarkWeekExported(arg1:string):Promise<void>;

export function ReorderTasks(arg1:Array<string>):Promise<void>;

export function SaveDay(arg1:string,arg2:Record<string, number>):Promise<void>;

export function SaveHTMLExport(arg1:string,arg2:string):Promise<string>;

export function SelectDirectory():Promise<string>;

export function SetExportPath(arg1:string):Promise<void>;

export function SetTaskType(arg1:string,arg2:string):Promise<void>;

export function UpdateTask(arg1:string,arg2:string):Promise<void>;
