// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTask(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddTask'](arg1, arg2, arg3);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function GetExportPath() {
  return window['go']['main']['App']['GetExportPath']();
}

export function GetMonthlyReport(arg1, arg2) {
  return window['go']['main']['App']['GetMonthlyReport'](arg1, arg2);
}

export function GetStreaks() {
  return window['go']['main']['App']['GetStreaks']();
}

export function GetTaskTemplates() {
  return window['go']['main']['App']['GetTaskTemplates']();
}

export function GetTasksForDate(arg1) {
  return window['go']['main']['App']['GetTasksForDate'](arg1);
}

export function GetWeeklyReport(arg1) {
  return window['go']['main']['App']['GetWeeklyReport'](arg1);
}

export function GetYearlyReport(arg1) {
  return window['go']['main']['App']['GetYearlyReport'](arg1);
}

export function IsWeekExported(arg1) {
  return window['go']['main']['App']['IsWeekExported'](arg1);
}

export function LoadDay(arg1) {
  return window['go']['main']['App']['LoadDay'](arg1);
}

export function LoadWeek(arg1) {
  return window['go']['main']['App']['LoadWeek'](arg1);
}

export function MarkWeekExported(arg1) {
  return window['go']['main']['App']['MarkWeekExported'](arg1);
}

export function ReorderTasks(arg1) {
  return window['go']['main']['App']['ReorderTasks'](arg1);
}

export function SaveDay(arg1, arg2) {
  return window['go']['main']['App']['SaveDay'](arg1, arg2);
}

export function SaveHTMLExport(arg1, arg2) {
  return window['go']['main']['App']['SaveHTMLExport'](arg1, arg2);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SetExportPath(arg1) {
  return window['go']['main']['App']['SetExportPath'](arg1);
}

export function SetTaskType(arg1, arg2) {
  return window['go']['main']['App']['SetTaskType'](arg1, arg2);
}

export function UpdateTask(arg1, arg2) {
  return window['go']['main']['App']['UpdateTask'](arg1, arg2);
}
